name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '00 00 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: 0ca0c0dc-7b1d-4195-8180-daebe48b052a
          GH_TOKEN: 35b820d1b3cd2dbe0360c4a6ce614ed381058ace
