name: Wakatime Stats

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  scheduled_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          WAKATIME_STAT_RANGE: ${{ secrets.WAKATIME_STAT_RANGE }}
          WAKATIME_ADD_INSIGHT: ${{ secrets.WAKATIME_ADD_INSIGHT }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: echo "Environment variables are set."

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the Wakatime Action
        uses: claserre9/wakatime-stats@master
