name: Wakatime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
#  print env secrets
  print-env-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print env secrets
        run:
          echo ${{ secrets.WAKATIME_USER_ID }}
          echo ${{ secrets.WAKATIME_API_KEY }}
          echo ${{ secrets.GH_TOKEN }}

  update-readme-with-wakatime-stats:
    name: Update this repo's README with stats
    runs-on: ubuntu-latest

    steps:
      - uses: claserre9/wakatime-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}