name: Wakatime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  update-readme-with-wakatime-stats:
    name: Update this repo's README with stats
    runs-on: ubuntu-latest

    steps:
      - uses: claserre9/wakatime-stats@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}